on:
  push:
    branches:
      - master

name: Deploy the app to GitHub pages

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install
      - name: Build
        run: |
          python tools/compose.py
          cd client
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./client/build
