on:
  pull_request:
    types: [opened, synchronize]

name: Run lint and test on pull requests

jobs:
  client-test:
    name: Client Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install
      - name: Run Lint
        working-directory: ${{ env.working-directory }}
        run: npm run lint
      - name: Run Test
        working-directory: ${{ env.working-directory }}
        run: npm run test:ci
  tools-test:
    name: Tools Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Lint
        run: pipenv run flake8 tools tests
      - name: Run Test
        run: pipenv run pytest tests
