name: Lint and Tests for Tools

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-test:
    name: Run Lint and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Run Lint for non-Python files
        run: ./dev/lint.sh
      - name: Run Lint for Python files
        run: ./dev/lint-python.sh
          ./dev/lint-python.sh
      - name: Run Tests
        run: ./dev/test.sh
